export { default as Home } from './Home'
export { default as AboutUs } from './AboutUs'
export { default as Services } from './Services'
export { default as Project } from './Project'
export { default as Insights } from './Insights'
export { default as Contact } from './Contact'